targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # Generates for files in lib/
          generate_for:
            - lib/**
